openapi: 3.0.0
info:
  title: Central Auth System
  version: 1.0.0
  description: API for central authentication

paths:
  /auth/signup:
    post:
      summary: Create user
      operationId: signup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
                - firstName
                - lastName
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                firstName:
                  type: string
                lastName:
                  type: string

      responses:
        '201':
          description: create user and send verification email
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                  - data
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'User created. Please check your email to verify your account'
                  data:
                    type: object
                    required:
                      - id
                      - email
                      - firstName
                      - lastName
                      - status
                      - emailVerified
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: '123e4567-e89b-12d3-a456-426614174000'
                      email:
                        type: string
                        format: email
                        example: 'user@example.com'
                      status:
                        type: string
                        enum:
                          [
                            PENDING,
                            ACTIVE,
                            SUSPENDED,
                            LOCKED,
                            DEACTIVATED,
                            DELETED,
                          ]
                        example: 'PENDING'
                      firstName:
                        type: string
                        example: 'John'
                      lastName:
                        type: string
                        example: 'Doe'
                      emailVerified:
                        type: boolean
                        example: true
        # Error responses (400 bad request, 409 conflict, ...)
        '400':
          description: Bad request (prisma errors)
          content:
            application/json:
              schema:
                type: object
                required:
                  - statusCode
                  - message
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'Invalie credentials'

        '409':
          description: Conflict exception(User with email already exists)
          content:
            application/json:
              schema:
                type: object
                required:
                  - statusCode
                  - message
                properties:
                  statusCode:
                    type: integer
                    example: 409
                  message:
                    type: string
                    example: 'User with this email already exists'
        '500':
          description: Internal server error

  /auth/verify-email:
    get:
      summary: Verify email
      operationId: verifyEmail
      parameters:
        - in: query
          name: token
          required: true
          description: Verification token sent to the user's email
          schema:
            type: string
            example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'
      responses:
        '200':
          description: Email verified successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - success
                  - message
                  - data
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: 'email verified successfully. You can log in'
        '400':
          description: Bat request (Token not found, Invalid or used token)
          content:
            application/json:
              schema:
                type: object
                required:
                  - statusCode
                  - message
                properties:
                  statusCode:
                    type: integer
                    example: 400
                  message:
                    type: string
                    example: 'Invalid or used token'

  /auth/login:
    post:
      summary: Login user
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: logint user
          content:
            application/json:
              schema:
                type: object
                required:
                  - accessToken
                  - refreshToken
                  - tokenType
                  - expiresIn
                properties:
                  acceptToken:
                    type: string
                    example: E3ODQ3MTYxMjksImV4cCI6MTc4NDcxNzAyOX0...
                  refreshToken:
                    type: string
                    example: 9uIjowLCJpYXQiOjE3ODQ3MTYxMjksImV4cCI6MTc4NzMwODEyOX0...
                  tokenType:
                    type: string
                    example: bearer
                  expiresIn:
                    type: number
                    example: 900

  /auth/refresh:
    post:
      summary: refresh token
  /auth/logout:
    post:
      summary: logout user
  /auth/sessions/:id/revoke:
    post:
      summary: revoke token
  /auth/sessions:
    get:
      summary: get sessions
  /auth/organizations:
    post:
      summary: create organization
  /auth/organizations/:id/invitations:
    post:
      summary: invite user to organization
  /auth/invitations/accept:
    post:
      summbary: accept invitation
  /auth/organizations/:id/members/role:
    patch: summary; assign role to user

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: 01KXG8848PVGZBKQKZ5S1H5J20
    Organization:
      type: object
    OrganizationMember:
      type: object
    Role:
      type: object
    Permission:
      type: object
    RolePermission:
      type: object
    Invitation:
      type: object
    Session:
      type: object
    UserToken:
      type: object
    AuditLog:
      type: object

  Errorresponse:
    type: object
